<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>spec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(\w+\:)</string>
			<key>name</key>
			<string>variable.parameter.spec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\%\{\w+\})</string>
			<key>name</key>
			<string>variable.other.spec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.makefile</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\%(description|prep|build|install|clean|files|changelog|preun|postun|pre|post))</string>
			<key>name</key>
			<string>meta.class.spec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\%(undefine|define|global|trace|dump|setup|patch|else|endif|(if((n)?(def|arch|os)?))|))</string>
			<key>name</key>
			<string>keyword.control.rpmspec</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.makefile</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.makefile</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\)\\$\n</string>
					<key>name</key>
					<string>punctuation.separator.continuation.makefile</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.spec</string>
	<key>uuid</key>
	<string>4EA7A9E8-90CB-4394-8E4C-722EE2F94AD7</string>
</dict>
</plist>
